server:
  port: 8080

spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;database=OnlineBookStore;encrypt=true;trustServerCertificate=true"
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 77fdf34f-8266-4aeb-97d9-6d1f710d108e