server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: "jdbc:sqlserver://localhost:1433;database=OnlineBookStore;encrypt=true;trustServerCertificate=true"
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    user:
      name: admin
  web:
    resources:
      static-locations: classpath:/static/
